# Generated by Django 4.1.7 on 2023-03-19 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunsmith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('share_setting', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PUB', max_length=3)),
                ('mode', models.CharField(choices=[('QP', 'Quickplay'), ('RA', 'Ranked'), ('WZ', 'Warzone')], default='QP', max_length=2)),
            ],
            options={
                'ordering': ['-created', 'receiver'],
            },
        ),
        migrations.AlterModelOptions(
            name='weaponreceiver',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddIndex(
            model_name='weaponreceiver',
            index=models.Index(fields=['category', 'platform'], name='gunsmith_we_categor_e4c994_idx'),
        ),
        migrations.AddField(
            model_name='weaponsetup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weaponsetup',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='gunsmith.weaponreceiver'),
        ),
        migrations.AddIndex(
            model_name='weaponsetup',
            index=models.Index(fields=['-created', 'author'], name='gunsmith_we_created_cf1c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='weaponsetup',
            index=models.Index(fields=['author', 'receiver'], name='gunsmith_we_author__72f334_idx'),
        ),
    ]
